import Link from 'next/link';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Profile, Skills, Credentials, ContactInvitation } from '@/components/profile';
import { LegacyFragments } from '@/components/legacy-fragments';
import { ProjectPreview } from '@/components/project-preview';
import { Testimonials } from '@/components/testimonials';
import { Icon } from '@/components/icon';
import { site, profile, publishedReviews } from '@/data/site';
export default function Home() {
  return <><a className="skip-link" href="#main">Skip to content</a><Header /><main id="main"><LegacyFragments /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'Person', name: site.name, url: site.url, jobTitle: 'Shopify Store Expert', image: site.profileSourceUrl, sameAs: [site.identity.instagramUrl] }).replace(/</g, '\u003c') }} /><Profile opening /><div className="reading-width"><section className="profile-content"><h2>About me</h2>{profile.aboutPreview.map(text => <p key={text}>{text}</p>)}<p className="about-cta"><Link href="/contact">{profile.aboutCta}</Link></p><Link className="text-link" href="/about">More about me<Icon name="ri-arrow-right-line" /></Link></section><Skills /><Credentials /></div><section className="container home-work"><div className="section-intro"><h2>Selected work</h2></div><div className="project-grid">{site.projects.filter(project => project.featured).map(project => <ProjectPreview key={project.id} project={project} />)}</div><Link className="text-link all-work-link" href="/work">View all work<Icon name="ri-arrow-right-line" /></Link></section><section className="container profile-content"><h2>What my clients say</h2><p className="review-count">{publishedReviews.length > 0 ? `${publishedReviews.length} published ${publishedReviews.length === 1 ? "review" : "reviews"}` : "Client feedback will be added here."}</p>{publishedReviews.length > 0 && <Testimonials reviews={publishedReviews.slice(0,8)} />}<div className="feedback-actions">{!publishedReviews.length && <Link className="text-link" href="/work">View my work<Icon name="ri-arrow-right-line" /></Link>}<Link className="text-link" href="/reviews">Read all reviews<Icon name="ri-arrow-right-line" /></Link></div></section><div className="container"><ContactInvitation /></div></main><Footer /></>;
}
