import Image from 'next/image';
import Link from 'next/link';
import { profile, site, type Credential } from '@/data/site';
import { Icon } from './icon';
import { LocalTime } from './local-time';
export function Profile({ opening = false }: { opening?: boolean }) {
  if (!opening) return <div className="compact-profile"><Image src={site.portrait.src} alt={site.portrait.alt} width={80} height={80} sizes="80px" /><div><Link href="/">{profile.name}</Link><p>{profile.title}</p></div></div>;
  return <section className="profile-section container" aria-labelledby="profile-name"><div className="profile-cover-frame"><Image className="profile-cover" src={site.banner.src} alt={site.banner.alt} width={site.banner.width} height={site.banner.height} sizes="(max-width: 767px) calc(100vw - 40px), 498px" priority /></div><div className="profile-identity"><Image className="profile-photo" src={site.portrait.src} alt={site.portrait.alt} width={152} height={152} sizes="(max-width: 767px) 120px, 152px" loading="eager" /><h1 id="profile-name">{profile.name}</h1><p className="profile-title">{profile.title}</p><p className="profile-introduction">{profile.introduction}</p><div className="profile-metadata">{profile.location && <span className="profile-detail"><Icon name="ri-map-pin-line" />{profile.location}</span>}<LocalTime />{profile.languages.length > 0 && <span className="profile-detail"><Icon name="ri-global-line" />{profile.languages.join(', ')}</span>}<span className="profile-detail"><span className="availability-dot" aria-hidden="true" />{profile.availability}</span></div><div className="profile-actions"><Link className="button" href="/contact">Contact me<Icon name="ri-arrow-right-up-line" /></Link><a className="button button-secondary" href={profile.contact.whatsappUrl}><Icon name="ri-whatsapp-line" />WhatsApp</a></div><div className="profile-socials"><a className="text-link" href={profile.contact.emailUrl}><Icon name="ri-mail-line" />Email me</a><a className="text-link" href={profile.contact.instagramUrl} target="_blank" rel="noopener noreferrer"><Icon name="ri-instagram-line" />Instagram<span className="sr-only"> (opens in a new tab)</span></a></div></div></section>;
}
export function Skills() { return <section className="profile-content" aria-labelledby="skills-title"><h2 id="skills-title">Skills</h2><ul className="skills-list">{profile.skills.map(skill => <li key={skill}>{skill}</li>)}</ul></section>; }
function CredentialSection({ title, icon, records }: { title: string; icon: string; records: Credential[] }) {
  if (!records.length) return null;
  return <section className="profile-content"><h2><Icon name={icon} />{title}</h2><ul className="credential-list">{records.map(record => <li key={record.title + record.institution}><h3>{record.url ? <a href={record.url} className="text-link" target="_blank" rel="noopener noreferrer">{record.title}<Icon name="ri-external-link-line" /><span className="sr-only"> (opens in a new tab)</span></a> : record.title}</h3><p>{record.institution}{record.period && ` · ${record.period}`}</p></li>)}</ul></section>;
}
export function Credentials() { return <><CredentialSection title="Education" icon="ri-graduation-cap-line" records={profile.education} /><CredentialSection title="Certifications" icon="ri-award-line" records={profile.certifications} /></>; }
export function ContactInvitation() { return <section className="contact-invitation"><div><h2>Let’s discuss your store.</h2><p>Tell me what you’re building, or what you’d like to improve.</p></div><Link className="button" href="/contact">Tell me about your store<Icon name="ri-arrow-right-up-line" /></Link></section>; }
