import Link from 'next/link';
import { PageShell } from '@/components/page-shell';
import { ContactInvitation } from '@/components/profile';
import { Icon } from '@/components/icon';
import { site } from '@/data/site';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Shopify services | Adex', 'Discuss a new Shopify store, a redesign or specific theme and usability improvements with me.', '/services');
const scope = ['Share your product range, brand materials and examples of the shopping experience you have in mind. We can discuss storefront setup, product organisation and navigation.', 'Send your store link and explain which layouts, menus or product pages need attention. Relevant examples help me understand the direction you want to take.', 'Share the pages or theme details you want to change, including any issues on mobile. Specific examples help us define what is included.'];
export default function ServicesPage() { return <PageShell><header className="page-heading"><h1>How I can help your store.</h1><p>{site.services.title}</p></header><div className="service-details">{site.services.items.map((service, index) => <section className="service-detail" key={service.title}><Icon name={service.icon} /><div><h2>{service.title}</h2><p>{service.description}</p><p>{scope[index]}</p><Link className="text-link" href={`/contact?service=${encodeURIComponent(site.contact.services[index])}`}>Discuss this service<Icon name="ri-arrow-right-line" /></Link></div></section>)}</div><section className="profile-content"><h2>{site.process.title}</h2><ol className="process-grid">{site.process.steps.map((step,index) => <li key={step.title}><span className="step-number">0{index+1}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol></section><section className="profile-content"><h2>{site.faq.title}</h2><div className="faq-list">{site.faq.items.map(item => <details key={item.question}><summary>{item.question}<Icon name="ri-add-line" /></summary><p>{item.answer}</p></details>)}</div></section><ContactInvitation /></PageShell>; }
